language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -vfi

script:
  - ./configure || { cat config.log; false; }
  - make
  - if test "${TRAVIS_OS_NAME}" = "linux"; then
      make distcheck;
    else
      make check;
    fi
    || { cat test/test-suite.log sample-*/_build/test/test-suite.log; false; }

deploy:
  provider: releases
  api_key:
    secure: "OTjY5FuRKj3EGC9Cw7Wi+DllGN8odQWfpcyuN7f9RVJW/wYUfpuZ2mXnXYCi0KtgmSMvQffCH5nLv9jlwbtup+ChWRuscftUtnMkmEo03l03k6q5uO5Avi1m9numCL9tAo0zuWweCrR2pNZMarvKl3IMSym88E+PTqubWD/vFx/QVQhXtuZ36U+kDoZS9Dh4E8C98QoJp3dYalweF0FjUSR1emC3YFEuKgNfrgEzA/+IXkOj671326p65mZ2UCwOU3tziSn/QsF6+c6dO8rcTTVYu00SZxO6laQU6y5WT6fcRkIlyGbGgw+xM/Ad7gdQk1StJV0MS06Wqc/zt02SFnAT5QEcC3v1ZjLr6Jw8HELw0LMISootY7N88KgTzTcXcj2020PNqRH438v/r71A1csKAxpfi0hUwEohVsBu+XbPynmWKb47O1OY2B9g+PiwJKwks4AwkRo9oGD8/6hwqe0YtJXYhbpwNw//A284ChB2nciLlgCTWb1Z6oECXckCctNDlFXytmH8oHnCokLMbC3w8lB1oCvcXiMU2A7Wol8qi1JN+uMXxJ2V6KV5yrgO5vzakR2wkxvWlqXRVjEmi+WZshGqUWProE2SxntRSonsjN6iZb3Yl5gk6P5FYn/3XybJ9WIkXiL5o5J8UVpIafLRcAPJD0NyW8T4u1VbuG8="
  file_glob: true
  file: sample-*.tar.xz
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    - devel@fresse.org
